### ISSUE TITLE
HdiCloudK8sServiceTests System.InvalidProgramException : Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by jakubch1** [microsoft/CLRInstrumentationEngine#443]
We got report about System.InvalidProgramException when using CLR IE. I've checked that issue is reproducible even without any code coverage instrumentation (ShouldInstrument => true, InstrumentMethod => return S_OK). Issue is for method: GetHdiPolicyValidationRequest. Attaching dump logs and full project so you can run it if needed:

[gethdipolicyvalidationrequest.csproj.txt](https://github.com/microsoft/CLRInstrumentationEngine/files/7257796/gethdipolicyvalidationrequest.csproj.txt)
[Tests.cs.txt](https://github.com/microsoft/CLRInstrumentationEngine/files/7257793/Tests.cs.txt)
[ProfilerLog_33052.txt](https://github.com/microsoft/CLRInstrumentationEngine/files/7257798/ProfilerLog_33052.txt)

Issue:
```
      Error Message:
   System.InvalidProgramException : Common Language Runtime detected an invalid program.
  Stack Trace:
     at GetHdiPolicyValidationRequest.PolicyUtilities.GetHdiPolicyValidationRequest(HdiJobMetadata job)
   at GetHdiPolicyValidationRequest.Tests.Test1() in D:\vscodecoverage\artifacts\test\c\5679e3c908c47c930132f4c395c0b5c76a1469e6805df7b05fbb13d22a04525f\Tests.cs:line 14
```

**Comment by jakubch1** [comment]
In this case I've changed our IM to not make any changes. So issue is on CLRIE side.

**Comment by jander-msft** [comment]
There are other ways that an instrumentation method can affect the IL outside of the InstrumenMethod. It can define types, methods, fields, properties, stubs, p/invokes, etc and sometimes write method bodies whole-sale without ever going through InstrumentMethod.

Please compare the difference between the IL of the method from the original assembly vs the IL that CLRIE says it generated to determine what the actual difference is and get a better idea of what is causing the issue.

**Comment by jakubch1** [comment]
This is original IL code:
```
.method public hidebysig static 
	class GetHdiPolicyValidationRequest.ValidationRequestDto GetHdiPolicyValidationRequest (
		class GetHdiPolicyValidationRequest.HdiJobMetadata job
	) cil managed 
{
	// Method begins at RVA 0x20bc
	// Code size 160 (0xa0)
	.maxstack 9
	.locals init (
		[0] class GetHdiPolicyValidationRequest.ValidationRequestDto validationRequest,
		[1] class GetHdiPolicyValidationRequest.ValidationRequestDto
	)

	IL_0000: nop
	IL_0001: newobj instance void GetHdiPolicyValidationRequest.ValidationRequestDto::.ctor()
	IL_0006: dup
	IL_0007: ldarg.0
	IL_0008: callvirt instance string GetHdiPolicyValidationRequest.HdiJobMetadata::get_ExperimentId()
	IL_000d: dup
	IL_000e: brtrue.s IL_001c

	IL_0010: pop
	IL_0011: ldsfld string [System.Runtime]System.String::Empty
	IL_0016: newobj instance void [System.Runtime]System.ArgumentNullException::.ctor(string)
	IL_001b: throw

	IL_001c: callvirt instance void GetHdiPolicyValidationRequest.ValidationRequestDto::set_ExperimentName(string)
	IL_0021: nop
	IL_0022: dup
	IL_0023: newobj instance void GetHdiPolicyValidationRequest.ExecutionContextDto::.ctor()
	IL_0028: dup
	IL_0029: newobj instance void GetHdiPolicyValidationRequest.ModuleInfoDto::.ctor()
	IL_002e: dup
	IL_002f: newobj instance void class [System.Collections]System.Collections.Generic.List`1<string>::.ctor()
	IL_0034: dup
	IL_0035: ldarg.0
	IL_0036: callvirt instance class GetHdiPolicyValidationRequest.ModuleInfoDto GetHdiPolicyValidationRequest.HdiJobMetadata::get_ModuleInfo()
	IL_003b: callvirt instance string GetHdiPolicyValidationRequest.ModuleInfoDto::get_ModuleId()
	IL_0040: callvirt instance void class [System.Collections]System.Collections.Generic.List`1<string>::Add(!0)
	IL_0045: nop
	IL_0046: callvirt instance void GetHdiPolicyValidationRequest.ModuleInfoDto::set_SnapshotIds(class [System.Collections]System.Collections.Generic.List`1<string>)
	IL_004b: nop
	IL_004c: dup
	IL_004d: ldarg.0
	IL_004e: callvirt instance string GetHdiPolicyValidationRequest.HdiJobMetadata::get_File()
	IL_0053: callvirt instance string [System.Runtime]System.String::ToLower()
	IL_0058: ldsfld string [System.Runtime]System.String::Empty
	IL_005d: callvirt instance bool [System.Runtime]System.String::EndsWith(string)
	IL_0062: brtrue.s IL_006b

	IL_0064: ldsfld string [System.Runtime]System.String::Empty
	IL_0069: br.s IL_0070

	IL_006b: ldsfld string [System.Runtime]System.String::Empty

	IL_0070: callvirt instance void GetHdiPolicyValidationRequest.ModuleInfoDto::set_Executable(string)
	IL_0075: nop
	IL_0076: dup
	IL_0077: ldsfld string [System.Runtime]System.String::Empty
	IL_007c: ldarg.0
	IL_007d: callvirt instance class [System.Collections]System.Collections.Generic.List`1<string> GetHdiPolicyValidationRequest.HdiJobMetadata::get_Args()
	IL_0082: call string [System.Runtime]System.String::Join(string, class [System.Runtime]System.Collections.Generic.IEnumerable`1<string>)
	IL_0087: callvirt instance void GetHdiPolicyValidationRequest.ModuleInfoDto::set_Arguments(string)
	IL_008c: nop
	IL_008d: callvirt instance void GetHdiPolicyValidationRequest.ExecutionContextDto::set_ModuleInfo(class GetHdiPolicyValidationRequest.ModuleInfoDto)
	IL_0092: nop
	IL_0093: callvirt instance void GetHdiPolicyValidationRequest.ValidationRequestDto::set_ExecutionContext(class GetHdiPolicyValidationRequest.ExecutionContextDto)
	IL_0098: nop
	IL_0099: stloc.0
	IL_009a: ldloc.0
	IL_009b: stloc.1
	IL_009c: br.s IL_009e

	IL_009e: ldloc.1
	IL_009f: ret
} // end of method PolicyUtilities::GetHdiPolicyValidationRequest
```

I compared both and apart of expected changes (brtrue.s -> brtrue) there are no changes in IL code. 

But maxstack in original method is 9 and in CLRIE logs I can see 8. So probably this is the issue. It's similar to: #304 and dotnet/runtime#51828
